### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by aaelony** [bob-carpenter/diagnostic-testing#2]
Caught a typo...

"this person is sampled at ramdom from a population" in https://github.com/bob-carpenter/diagnostic-testing/blob/master/src/specificity-santa-clara/specificity.tex

**Comment by aaelony** [comment]
and another one: "it coud be improved by including interactions"

**Comment by aaelony** [comment]
one more: "is has" => "has"

**Comment by bob-carpenter** [comment]
Thanks.  I fixed these and pushed and ran everything through a spell checker.

**Comment by aaelony** [comment]
I really like the way the paper reads. Cool.  But maybe my screen still shows "coud" instead of "could".  Weird.

https://github.com/bob-carpenter/diagnostic-testing/blob/master/src/specificity-santa-clara/specificity.tex#L222

**Comment by bob-carpenter** [comment]
We're in the middle of revising the paper and haven't pushed a new one to the web site.  The one on GitHub should be updated.

**Comment by bob-carpenter** [comment]
Ack.  I'm wrong.  How'd my spell checker miss "coud"?  Maybe it's a kind of bird from New Zealand or something?  We'll fix it.

**Comment by aaelony** [comment]
Hahah. Cool. Sorry for being annoying.. Awesome paper!
